name = ""
avatar = "images/logo.png" # Avatar image. Default to "images/profile.webp".
bio = "Site de la communauté francophone des utilisateurs du logiciel darktable"
# company = 'Company'
# company = '<a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>'
# location = "Earth"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  layout = "compact"

#[social]
  #email = "admin@darktable.fr"
  #facebook = "yourfacebookusername"
  #github = "darktable-fr"
  #twitter = "darktable_fr"
  #linkedin = "yourlinkedinusername"
  #liberapay = "darktable.fr"
  #paypal="andycostanza"
  #patreon="darktablefr"
  #tipeee="darktable-fr"
